DROP DATABASE IF EXISTS example;

CREATE DATABASE IF NOT EXISTS example;

USE example;

CREATE TABLE IF NOT EXISTS `logs` (
	`id` INT(4) NOT NULL PRIMARY KEY AUTO_INCREMENT COMMENT 'The log Id',
	`message` VARCHAR(255) NOT NULL COMMENT 'The log message',
	`type` INT(4) NOT NULL COMMENT 'The log type'
) ENGINE = InnoDB AUTO_INCREMENT = 1;
